/************************************************************/
/*     ZAPL_AppsLayer.h                                     */
/*     AppsLayer State transition model header file         */
/*     ZIPC Designer Version 1.2.0                          */
/************************************************************/
#ifndef ZHEADER_ZAPL_APPSLAYER_H
#define ZHEADER_ZAPL_APPSLAYER_H

/*State management variable access define*/
#define ZAPL_APPSLAYER ( 0U )
#define ZAPL_APPSLAYERS0F ( 1U )
#define ZAPL_APPSLAYERS1F ( 2U )
#define ZAPL_APPSLAYERS0 ( 0U )
#define ZAPL_RESTRICTIONMODEOFFS0 ( 0U )
#define ZAPL_RESTRICTIONMODEOFFS1 ( 1U )
#define ZAPL_RESTRICTIONMODEOFFS2 ( 2U )
#define ZAPL_RESTRICTIONMODEOFFS3 ( 3U )
#define ZAPL_RESTRICTIONMODEOFFS4 ( 4U )
#define ZAPL_RESTRICTIONMODEOFFS5 ( 5U )
#define ZAPL_RESTRICTIONMODEOFFS6 ( 6U )
#define ZAPL_RESTRICTIONMODEOFFS7 ( 7U )
#define ZAPL_APPSLAYERS1 ( 1U )
#define ZAPL_RESTRICTIONMODEONS0 ( 0U )
#define ZAPL_RESTRICTIONMODEONS1 ( 1U )
#define ZAPL_APPSLAYERSTATENOMAX ( 3U )

/*End state define*/
#define ZAPL_APPSLAYEREND ( 8U )
/*Terminate state define*/
#define ZAPL_APPSLAYERTERMINATE ( ZAPL_APPSLAYEREND + 1U )

/*State no define*/
#define ZAPL_APPSLAYERS0STATENO ( 0U )
#define ZAPL_RESTRICTIONMODEOFFS0STATENO ( 0U )
#define ZAPL_RESTRICTIONMODEOFFS1STATENO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFS2STATENO ( 2U )
#define ZAPL_RESTRICTIONMODEOFFS3STATENO ( 3U )
#define ZAPL_RESTRICTIONMODEOFFS4STATENO ( 4U )
#define ZAPL_RESTRICTIONMODEOFFS5STATENO ( 5U )
#define ZAPL_RESTRICTIONMODEOFFS6STATENO ( 6U )
#define ZAPL_RESTRICTIONMODEOFFS7STATENO ( 7U )
#define ZAPL_APPSLAYERS1STATENO ( 1U )
#define ZAPL_RESTRICTIONMODEONS0STATENO ( 0U )
#define ZAPL_RESTRICTIONMODEONS1STATENO ( 1U )

/*State serial no define*/
#define ZAPL_APPSLAYERS0STATESERIALNO ( 0U )
#define ZAPL_RESTRICTIONMODEOFFS0STATESERIALNO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFS1STATESERIALNO ( 2U )
#define ZAPL_RESTRICTIONMODEOFFS2STATESERIALNO ( 3U )
#define ZAPL_RESTRICTIONMODEOFFS3STATESERIALNO ( 4U )
#define ZAPL_RESTRICTIONMODEOFFS4STATESERIALNO ( 5U )
#define ZAPL_RESTRICTIONMODEOFFS5STATESERIALNO ( 6U )
#define ZAPL_RESTRICTIONMODEOFFS6STATESERIALNO ( 7U )
#define ZAPL_RESTRICTIONMODEOFFS7STATESERIALNO ( 8U )
#define ZAPL_APPSLAYERS1STATESERIALNO ( 9U )
#define ZAPL_RESTRICTIONMODEONS0STATESERIALNO ( 10U )
#define ZAPL_RESTRICTIONMODEONS1STATESERIALNO ( 11U )

/*Event no define*/
#define ZAPL_APPSLAYERE0EVENTNO ( 0U )
#define ZAPL_APPSLAYERE1EVENTNO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFE0EVENTNO ( 0U )
#define ZAPL_RESTRICTIONMODEOFFE1EVENTNO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFE2EVENTNO ( 2U )
#define ZAPL_RESTRICTIONMODEOFFE3EVENTNO ( 3U )
#define ZAPL_RESTRICTIONMODEOFFE4EVENTNO ( 4U )
#define ZAPL_RESTRICTIONMODEOFFE5EVENTNO ( 5U )
#define ZAPL_RESTRICTIONMODEOFFE6EVENTNO ( 6U )
#define ZAPL_RESTRICTIONMODEOFFE7EVENTNO ( 7U )
#define ZAPL_RESTRICTIONMODEOFFE8EVENTNO ( 8U )
#define ZAPL_RESTRICTIONMODEOFFE9EVENTNO ( 9U )
#define ZAPL_RESTRICTIONMODEOFFE10EVENTNO ( 10U )
#define ZAPL_RESTRICTIONMODEOFFE11EVENTNO ( 11U )
#define ZAPL_RESTRICTIONMODEOFFE12EVENTNO ( 12U )
#define ZAPL_RESTRICTIONMODEOFFE13EVENTNO ( 13U )
#define ZAPL_RESTRICTIONMODEOFFE14EVENTNO ( 14U )
#define ZAPL_RESTRICTIONMODEOFFE15EVENTNO ( 15U )
#define ZAPL_RESTRICTIONMODEOFFE16EVENTNO ( 16U )
#define ZAPL_RESTRICTIONMODEOFFE17EVENTNO ( 17U )
#define ZAPL_RESTRICTIONMODEOFFE18EVENTNO ( 18U )
#define ZAPL_RESTRICTIONMODEOFFE19EVENTNO ( 19U )
#define ZAPL_RESTRICTIONMODEOFFE20EVENTNO ( 20U )
#define ZAPL_RESTRICTIONMODEONE0EVENTNO ( 0U )
#define ZAPL_RESTRICTIONMODEONE1EVENTNO ( 1U )
#define ZAPL_RESTRICTIONMODEONE2EVENTNO ( 2U )
#define ZAPL_RESTRICTIONMODEONE3EVENTNO ( 3U )

/*Event serial no define*/
#define ZAPL_APPSLAYERE0EVENTSERIALNO ( 0U )
#define ZAPL_APPSLAYERE1EVENTSERIALNO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFE0EVENTNO ( 0U )
#define ZAPL_RESTRICTIONMODEOFFE1EVENTNO ( 1U )
#define ZAPL_RESTRICTIONMODEOFFE2EVENTNO ( 2U )
#define ZAPL_RESTRICTIONMODEOFFE3EVENTNO ( 3U )
#define ZAPL_RESTRICTIONMODEOFFE4EVENTNO ( 4U )
#define ZAPL_RESTRICTIONMODEOFFE5EVENTNO ( 5U )
#define ZAPL_RESTRICTIONMODEOFFE6EVENTNO ( 6U )
#define ZAPL_RESTRICTIONMODEOFFE7EVENTNO ( 7U )
#define ZAPL_RESTRICTIONMODEOFFE8EVENTNO ( 8U )
#define ZAPL_RESTRICTIONMODEOFFE9EVENTNO ( 9U )
#define ZAPL_RESTRICTIONMODEOFFE10EVENTNO ( 10U )
#define ZAPL_RESTRICTIONMODEOFFE11EVENTNO ( 11U )
#define ZAPL_RESTRICTIONMODEOFFE12EVENTNO ( 12U )
#define ZAPL_RESTRICTIONMODEOFFE13EVENTNO ( 13U )
#define ZAPL_RESTRICTIONMODEOFFE14EVENTNO ( 14U )
#define ZAPL_RESTRICTIONMODEOFFE15EVENTNO ( 15U )
#define ZAPL_RESTRICTIONMODEOFFE16EVENTNO ( 16U )
#define ZAPL_RESTRICTIONMODEOFFE17EVENTNO ( 17U )
#define ZAPL_RESTRICTIONMODEOFFE18EVENTNO ( 18U )
#define ZAPL_RESTRICTIONMODEOFFE19EVENTNO ( 19U )
#define ZAPL_RESTRICTIONMODEOFFE20EVENTNO ( 20U )
#define ZAPL_RESTRICTIONMODEONE0EVENTNO ( 0U )
#define ZAPL_RESTRICTIONMODEONE1EVENTNO ( 1U )
#define ZAPL_RESTRICTIONMODEONE2EVENTNO ( 2U )
#define ZAPL_RESTRICTIONMODEONE3EVENTNO ( 3U )

/*Extern function*/
extern void stm_apl_event_call( void );
extern void stm_apl_initialize( void );
extern void ZAPL_AppsLayerTerminate( void );

#endif
