#!/bin/sh

#
# Copyright (c) 2017 TOYOTA MOTOR CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

nopygments=0
if [ "$1" = "-p" ]
then
   nopygments=1
   shift
fi

if ! [ "$1" ]
then
   echo "Usage: $0 VERB [ARGS]" >&2
   exit 1
fi

UUIDFILE=/tmp/wm-request-uuid
if ! which uuidgen 2>/dev/null 1>&2
then
   echo "c7c638c5-d097-4eb4-9012-a1e4c25b9808" > $UUIDFILE
else
   if ! [ -f $UUIDFILE ]
   then
      uuidgen > $UUIDFILE
   fi
fi
UUID="`cat $UUIDFILE`"

for i in afb-client-demo
do
   which $i 2>/dev/null 1>&2 || { echo "Program $i is missing" >&2; exit 1; }
done

set -eu

   if [ $nopygments = 0 ] && which pygmentize 2>/dev/null 1>&2
   then
      json_pretty() {
      pygmentize -l json
      }
   else
      json_pretty() {
      cat
   }
fi

verb=$1
shift

set +u
if [ "$1" ]
then
   set -u
   args='{"drawing_name":"'"$1"'"}'
fi

afb-client-demo -H ws://localhost:1700/api\?token=wm\&uuid=$UUID windowmanager $verb $args | json_pretty

# vim:set ft=sh:
